# Generated by Django 4.2.7 on 2023-12-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=10)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("in_clinic", "In Clinic"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        default="in_clinic",
                        max_length=20,
                    ),
                ),
                ("appointment_time", models.TimeField(help_text="Format: HH:MM")),
            ],
        ),
    ]
